pool:
  vmImage: 'VS2017-Win2016'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Pack1Version: '1.0.0'
  Pack1PushToNuget: False
  Pack2Version: '1.0.0'
  Pack2PushToNuget: True

steps:
# Install NuGet Tool
- task: NuGetToolInstaller@0
  displayName: Install NuGet Tool

# Restore NuGet packages
- task: NuGetCommand@2
  displayName: Restore NuGet Packages
  inputs:
    restoreSolution: '$(solution)'

# Build solution
- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Run unit tests
- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Prepare publish files
- task: DotNetCoreCLI@2
  displayName: Prepare Publish Files
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/**/Marco.Extensions.*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: False  

# Publish the artifacts
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts

# Publish Marco.Extensions.Configuration to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack Marco.Extensions.Configuration
  condition: eq(variables['Pack1PushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/Marco.Extensions.Configuration.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: Pack1Version
- task: NuGetCommand@2
  displayName: Push Marco.Extensions.Configuration to NuGet.org
  condition: eq(variables['Pack1PushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/Marco.Extensions.Configuration.*.nupkg'
    publishFeedCredentials: 'apikey-nuget-marco-configuration-extensions'
    
# Publish Marco.Extensions.ConnectionStringBuilder to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack Marco.Extensions.ConnectionStringBuilder
  condition: eq(variables['Pack2PushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/Marco.Extensions.ConnectionStringBuilder.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: Pack2Version
- task: NuGetCommand@2
  displayName: Push Marco.Extensions.ConnectionStringBuilder to NuGet.org
  condition: eq(variables['Pack2PushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/Marco.Extensions.ConnectionStringBuilder.*.nupkg'
    publishFeedCredentials: 'apikey-nuget-marcoconnectionstringbuilder'
